#!/bin/bash
# 03-generate-validator-keys.sh
# Generate validator keystores using eth2-val-tools

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

echo "=============================================="
echo "  Ethereum Devnet - Validator Key Generation"
echo "=============================================="
echo

# Check prerequisites
validate_data_exists "Genesis config" "${GENESIS_DIR}/config.yaml"

# Check if keys already exist
if [[ -d "${KEYS_DIR}/validators" ]] && [[ -n "$(ls -A ${KEYS_DIR}/validators 2>/dev/null)" ]]; then
    log_warn "Validator keys already exist"
    read -p "Do you want to regenerate them? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Keeping existing validator keys"
        exit 0
    fi
    rm -rf "${KEYS_DIR:?}/"*
fi

# Create directories
mkdir -p "${KEYS_DIR}/validators"
mkdir -p "${KEYS_DIR}/secrets"

log_info "Generating ${NUM_VALIDATORS} validator keys..."
log_info "Using mnemonic for reproducible keys (development only)"
if [[ ${NUM_VALIDATORS} -gt 512 ]]; then
    log_warn "${NUM_VALIDATORS} keystores use a scrypt KDF - this can take several minutes"
fi

# Create a temporary directory for key generation
TEMP_DIR=$(mktemp -d)
trap "rm -rf ${TEMP_DIR}" EXIT

# Generate validator keys using eth2-val-tools
docker run --rm \
    -v "${TEMP_DIR}:/output" \
    "${ETH2_VAL_TOOLS_IMAGE}" \
    keystores \
    --out-loc=/output/keys \
    --source-mnemonic="${VALIDATOR_MNEMONIC}" \
    --source-min=0 \
    --source-max=$((NUM_VALIDATORS - 1))

log_success "Keys generated"

# Copy keys to the proper location
log_info "Organizing validator keys..."

# eth2-val-tools outputs to:
#   keys/keys/0x<pubkey>/voting-keystore.json  (keystores)
#   keys/secrets/0x<pubkey>                     (password files)

KEYS_OUTPUT="${TEMP_DIR}/keys/keys"
SECRETS_OUTPUT="${TEMP_DIR}/keys/secrets"

VALIDATOR_INDEX=0
for keystore_dir in "${KEYS_OUTPUT}"/0x*/; do
    if [[ -d "$keystore_dir" ]]; then
        PUBKEY=$(basename "$keystore_dir")
        KEYSTORE_FILE="${keystore_dir}/voting-keystore.json"
        SECRET_FILE="${SECRETS_OUTPUT}/${PUBKEY}"

        if [[ -f "$KEYSTORE_FILE" ]]; then
            # Create validator directory and copy keystore
            VALIDATOR_DIR="${KEYS_DIR}/validators/${PUBKEY}"
            mkdir -p "$VALIDATOR_DIR"
            cp "$KEYSTORE_FILE" "${VALIDATOR_DIR}/voting-keystore.json"

            # Copy password file (generated by eth2-val-tools)
            if [[ -f "$SECRET_FILE" ]]; then
                cp "$SECRET_FILE" "${KEYS_DIR}/secrets/${PUBKEY}"
            fi

            ((VALIDATOR_INDEX++))
        fi
    fi
done

# Alternative: use Lighthouse's validator import
# First, let's create keystores in Lighthouse's expected format
log_info "Setting up Lighthouse validator data directory..."

# Create validator definitions for Lighthouse
VALIDATOR_DEFS="${CL_DATA_DIR}/validator/validators"
mkdir -p "$VALIDATOR_DEFS"

# Copy the organized keys
cp -r "${KEYS_DIR}/validators/"* "$VALIDATOR_DEFS/" 2>/dev/null || true
cp -r "${KEYS_DIR}/secrets" "${CL_DATA_DIR}/validator/" 2>/dev/null || true

log_success "Validator keys organized"

echo
echo "=============================================="
log_success "Validator key generation complete!"
echo "=============================================="
echo
echo "Generated ${VALIDATOR_INDEX} validator keystores"
echo
echo "Key locations:"
echo "  - Keystores: ${KEYS_DIR}/validators/"
echo "  - Secrets:   ${KEYS_DIR}/secrets/"
echo
echo "Note: These keys use a well-known development mnemonic."
echo "DO NOT use these keys on mainnet or with real funds!"
echo
echo "Next step: Run ./04-start-execution-layer.sh"
